export const REPLAN_PHASE_MS = {
  FREEZING: 200,
  DECONSTRUCTING: 400,
  GENERATING: 800,
  ANIMATING: 600,
  DONE: 200,
} as const;

export const REPLAN_CARD_STAGGER_MS = 80;
export const REPLAN_NEW_BADGE_TTL_MS = 3000;
export const REPLAN_POST_SUMMARY_HIDE_MS = 3000;
export const REPLAN_OVERLAY_FADE_S = 0.18;
export const REPLAN_MAP_DIM_OPACITY = 0.35;
export const REPLAN_MAP_ROUTE_FADE_S = 0.28;
export const REPLAN_CARD_ENTER_DURATION_S = 0.35;
export const REPLAN_GENERATING_LOG_STEP_MS = 200;
export const REPLAN_SPINNER_PERIOD_MS = 900;
export const REPLAN_FREEZING_BLUR_PX = 2;
export const REPLAN_VERTICAL_FREEZING_OPACITY = 0.45;
export const REPLAN_VERTICAL_EXIT_X = 40;
export const REPLAN_VERTICAL_EXIT_SCALE = 0.98;
export const REPLAN_VERTICAL_ENTER_Y = 20;

export const REPLAN_T_FREEZING_END = REPLAN_PHASE_MS.FREEZING;
export const REPLAN_T_DECONSTRUCTING_END =
  REPLAN_T_FREEZING_END + REPLAN_PHASE_MS.DECONSTRUCTING;
export const REPLAN_T_GENERATING_END =
  REPLAN_T_DECONSTRUCTING_END + REPLAN_PHASE_MS.GENERATING;
export const REPLAN_T_ANIMATING_END =
  REPLAN_T_GENERATING_END + REPLAN_PHASE_MS.ANIMATING;
export const REPLAN_T_DONE_END = REPLAN_T_ANIMATING_END + REPLAN_PHASE_MS.DONE;

export const REPLAN_GENERATING_LOG_MESSAGES = [
  "正在寻找等待更短、适合孩子的替代活动...",
  "找到几个低等待地点，正在比较距离和亲子友好度...",
  "正在尽量保留晚餐和返程时间...",
  "新的轻松路线已经整理好。",
] as const;

export const REPLAN_POST_SUMMARY_MESSAGE =
  "已缩短高等待活动，并插入更稳妥的替代地点。晚餐与返程时间保持稳定。";

export const REPLAN_GENERATING_OVERLAY_TITLE = "正在帮你调整安排...";
